### ISSUE TITLE
Implement FittedAV

### ISSUE THREAD

**Issue by f4lco** [tim-friedrich/DYOD_WS1718_Sprint1#3]
Sprint 2 mandates an attribute vector with variable width. Check the sheet for instructions and implement.

**Comment by f4lco** [comment]
You'll probably want to rename and adapt the current `SimpleAttributeVector` implementing a fixed-width strategy since it is conceptually superseded by the variably sized AV (and any 'extra' implementation artifacts should not appear in the review diff).

**Comment by tim-friedrich** [comment]
see pull request
